 pipeline {
    agent any

  stages {
    stage('initial cleanup') {
      steps{
        dir("$(WORKSPACE)") {
          deleteDir()
        }
      }
    }

    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    
    stage('package') {
      steps{
        script {
          sh 'echo "packaging stage"'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploy stage"'  
        }
      }
    }

    stage('Cleanup') {
      steps {
        CleanWS()
      }
    }

  }


